import { Presentation } from '../types/presentation';

export const demoPresentation: Presentation = {
  title: 'SlideCraft — Демонстрация возможностей',
  slides: [
    // ---------- SLIDE 1 / HERO ----------
    {
      id: 'demo1',
      background: { type: 'color', value: '#0f172a' },
      elements: [
        {
          id: 'title1',
          type: 'text',
          content: 'SlideCraft',
          fontSize: 76,
          font: 'Arial, sans-serif',
          color: '#6366f1',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1,
          placeholder: '',
          position: { x: 50, y: 150 },
          size: { width: 900, height: 120 },
        },
        {
          id: 'subtitle1',
          type: 'text',
          content: 'Создавай впечатляющие презентации',
          fontSize: 28,
          font: 'Arial, sans-serif',
          color: '#22d3ee',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.3,
          placeholder: '',
          position: { x: 150, y: 280 },
          size: { width: 700, height: 60 },
        },
        {
          id: 'text1',
          type: 'text',
          content:
            'Полнофункциональный онлайн-редактор презентаций\nС акцентом на удобство и производительность',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#94a3b8',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.5,
          placeholder: '',
          position: { x: 100, y: 370 },
          size: { width: 800, height: 100 },
        },
      ],
    },

    // ---------- SLIDE 2 / ИНТЕРФЕЙС И ПАНЕЛИ ----------
    {
      id: 'demo2',
      background: { type: 'color', value: '#1e1b4b' },
      elements: [
        {
          id: 'title2',
          type: 'text',
          content: '📐 Интуитивный интерфейс',
          fontSize: 48,
          font: 'Arial, sans-serif',
          color: '#a855f7',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          position: { x: 80, y: 70 },
          size: { width: 800, height: 80 },
        },
        {
          id: 'feature1',
          type: 'text',
          content:
            '• Гибкая лента инструментов\n• Две основные вкладки: "Главная" и "Вставка"\n• Быстрый доступ к основным функциям\n• Визуальные разделители для навигации',
          fontSize: 22,
          font: 'Arial, sans-serif',
          color: '#e0e7ff',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 100, y: 170 },
          size: { width: 500, height: 220 },
        },
        {
          id: 'image1',
          type: 'image',
          src: 'https://legasoft.ru/upload/iblock/eb5/ec2y7js2dc1l81g694my2q7lmlacrnpw.png',
          position: { x: 620, y: 170 },
          size: { width: 300, height: 220 },
        },
        {
          id: 'footer2',
          type: 'text',
          content:
            'Вкладка "Главная": Добавление слайдов, работа с текстом, оформление\nВкладка "Вставка": Текст, изображения (файл/ссылка)',
          fontSize: 16,
          font: 'Arial, sans-serif',
          color: '#c7d2fe',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.4,
          position: { x: 80, y: 430 },
          size: { width: 840, height: 50 },
        },
      ],
    },

    // ---------- SLIDE 3 / РАБОТА С ТЕКСТОМ ----------
    {
      id: 'demo3',
      background: { type: 'color', value: '#0f172a' },
      elements: [
        {
          id: 'title3',
          type: 'text',
          content: '🔤 Полный контроль над текстом',
          fontSize: 46,
          font: 'Arial, sans-serif',
          color: '#22d3ee',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          lineHeight: 1.2,
          backgroundColor: 'transparent',
          position: { x: 130, y: 60 },
          size: { width: 700, height: 70 },
        },
        {
          id: 'text3',
          type: 'text',
          content: '✨ Богатое форматирование:',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#f8fafc',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 40, y: 150 },
          size: { width: 400, height: 40 },
        },
        {
          id: 'feature3',
          type: 'text',
          content:
            '𝐁 Жирный | 𝑰 Курсив | U Подчеркнутый\n🔠 Размер текста\n🎨 Цвет текста\n↔️ Выравнивание (влево, центр, вправо)\n↕️ Межстрочный интервал',
          fontSize: 22,
          font: 'Arial, sans-serif',
          color: '#cbd5e1',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 40, y: 210 },
          size: { width: 650, height: 180 },
        },
        {
          id: 'image3',
          type: 'image',
          src: 'https://avatars.mds.yandex.net/i?id=931b019edc43873ca44186f841f63ba1_l-5487857-images-thumbs&n=13',
          position: { x: 570, y: 150 },
          size: { width: 350, height: 240 },
        },
        {
          id: 'footer3',
          type: 'text',
          content: 'Выделяйте главное, структурируйте информацию, создавайте акценты',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#38bdf8',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: true,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.4,
          position: { x: 150, y: 430 },
          size: { width: 700, height: 40 },
        },
      ],
    },

    // ---------- SLIDE 4 / ВСТАВКА И РАБОТА С ЭЛЕМЕНТАМИ ----------
    {
      id: 'demo4',
      background: { type: 'color', value: '#1e293b' },
      elements: [
        {
          id: 'title4',
          type: 'text',
          content: '🧩 Вставка и управление элементами',
          fontSize: 44,
          font: 'Arial, sans-serif',
          color: '#3b82f6',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          position: { x: 100, y: 70 },
          size: { width: 800, height: 70 },
        },
        {
          id: 'list4',
          type: 'text',
          content:
            '📝 Добавление текстовых блоков\n🖼️ Загрузка изображений с компьютера\n🔗 Вставка картинок по URL-ссылке\n🎨 Изменение заливки фона слайда\n🧱 Заливка фигур (для будущих релизов)',
          fontSize: 22,
          font: 'Arial, sans-serif',
          color: '#e2e8f0',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 100, y: 170 },
          size: { width: 450, height: 240 },
        },
        {
          id: 'image4a',
          type: 'image',
          src: 'https://avatars.mds.yandex.net/i?id=9b406e580ded14c3e598214c5a2bb4cad22579dc-5887660-images-thumbs&n=13',
          position: { x: 600, y: 170 },
          size: { width: 120, height: 120 },
        },
        {
          id: 'image4b',
          type: 'image',
          src: 'https://helpx.adobe.com/content/dam/help/en/illustrator/how-to/icon-design/jcr_content/main-pars/image7/icon-design-fig6a.jpg',
          position: { x: 740, y: 170 },
          size: { width: 120, height: 120 },
        },
        {
          id: 'image4c',
          type: 'image',
          src: 'https://habrastorage.org/getpro/habr/upload_files/fb1/3fc/75d/fb13fc75db3b338ef6a2a4e31674fbc0.jpg',
          position: { x: 600, y: 310 },
          size: { width: 120, height: 120 },
        },
        {
          id: 'image4d',
          type: 'image',
          src: 'https://avatars.mds.yandex.net/i?id=3697fb42d7a52c3e07c1666ff10401f5_l-12463602-images-thumbs&n=13',
          position: { x: 740, y: 310 },
          size: { width: 120, height: 120 },
        },
      ],
    },

    // ---------- SLIDE 5 / АККАУНТ И ДАННЫЕ ----------
    {
      id: 'demo5',
      background: { type: 'color', value: '#1e1b4b' },
      elements: [
        {
          id: 'title5',
          type: 'text',
          content: '👤 Учетная запись и работа с данными',
          fontSize: 46,
          font: 'Arial, sans-serif',
          color: '#8b5cf6',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          position: { x: 80, y: 70 },
          size: { width: 840, height: 70 },
        },
        {
          id: 'feature5',
          type: 'text',
          content:
            '🔐 Безопасная регистрация и вход\n📊 Личный кабинет со списком презентаций\n✅ Валидация данных при загрузке\n💾 Автоматическое и ручное сохранение\n🔄 Undo/Redo (Ctrl+Z / Ctrl+Y)\n📋 Копирование/вставка элементов и слайдов',
          fontSize: 21,
          font: 'Arial, sans-serif',
          color: '#ddd6fe',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 100, y: 170 },
          size: { width: 500, height: 280 },
        },
        {
          id: 'image5',
          type: 'image',
          src: 'https://avatars.mds.yandex.net/i?id=1167514f637ba903e282d1b858b3adab_l-5222233-images-thumbs&n=13',
          position: { x: 640, y: 190 },
          size: { width: 260, height: 180 },
        },
        {
          id: 'footer5',
          type: 'text',
          content: 'Ваши работы всегда в безопасности и доступны с любого устройства',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#a78bfa',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: true,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.4,
          position: { x: 150, y: 430 },
          size: { width: 700, height: 40 },
        },
      ],
    },

    // ---------- SLIDE 6 / УВЕДОМЛЕНИЯ И UX ----------
    {
      id: 'demo6',
      background: { type: 'color', value: '#0f172a' },
      elements: [
        {
          id: 'title6',
          type: 'text',
          content: '💬 Умная система уведомлений',
          fontSize: 52,
          font: 'Arial, sans-serif',
          color: '#10b981',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          position: { x: 100, y: 40 },
          size: { width: 750, height: 70 },
        },
        {
          id: 'text6',
          type: 'text',
          content: 'Информативные сообщения на всех этапах:',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#d1fae5',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.5,
          position: { x: 120, y: 170 },
          size: { width: 400, height: 40 },
        },
        {
          id: 'list6',
          type: 'text',
          content:
            '✅ Успешная регистрация и вход\n📂 Загрузка и сохранение презентаций\n🖼️ Работа с изображениями\n⚠️ Обработка ошибок (некорректные данные, сеть)\n🎯 Контекстные подсказки',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#a7f3d0',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 140, y: 230 },
          size: { width: 400, height: 200 },
        },
        {
          id: 'image6',
          type: 'image',
          src: 'https://d37e98a2-3644-435d-b7be-ef61b4252a03.selcdn.net/uo/aiwoo_uo16/images/big/fa/89/fa89b25ddb495a9556a71fcf2b91a6e2.jpg',
          position: { x: 580, y: 170 },
          size: { width: 320, height: 220 },
        },
        {
          id: 'footer6',
          type: 'text',
          content: 'Пользователь всегда в курсе происходящего',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#34d399',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.4,
          position: { x: 150, y: 430 },
          size: { width: 700, height: 40 },
        },
      ],
    },

    // ---------- SLIDE 7 / ПЕРСПЕКТИВЫ И ПРИЗЫВ ----------
    {
      id: 'demo7',
      background: { type: 'color', value: ' #1e1b4b ' },
      elements: [
        {
          id: 'title7',
          type: 'text',
          content: '🚀 SlideCraft — это только начало!',
          fontSize: 58,
          font: 'Arial, sans-serif',
          color: '#f59e0b',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          position: { x: 50, y: 40 },
          size: { width: 900, height: 100 },
        },
        {
          id: 'text7',
          type: 'text',
          content: 'Уже работает стабильно и эффективно:',
          fontSize: 26,
          font: 'Arial, sans-serif',
          color: '#fde68a',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.4,
          position: { x: 150, y: 160 },
          size: { width: 700, height: 50 },
        },
        {
          id: 'list7',
          type: 'text',
          content:
            '✓ Редактор слайдов и элементов\n✓ Форматирование текста\n✓ Работа с изображениями\n✓ Система аккаунтов и сохранения\n✓ Undo/Redo и копирование\n✓ Удобные уведомления',
          fontSize: 22,
          font: 'Arial, sans-serif',
          color: '#fef3c7',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          position: { x: 200, y: 210 },
          size: { width: 600, height: 180 },
        },
        {
          id: 'cta7',
          type: 'text',
          content: 'Начните создавать свои впечатляющие презентации прямо сейчас!',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#fbbf24',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.3,
          position: { x: 100, y: 450 },
          size: { width: 800, height: 60 },
        },
      ],
    },
  ],
  currentSlideId: 'demo1',
  selectedSlideIds: ['demo1'],
};
