import { Presentation } from '../types/presentation';
import { DESIGN_THEMES } from '../../common/components/Toolbar/constants/designThemes';
import { applyListTypeToText } from '../functions/presentation';
import logoImage from '../../common/components/Toolbar/assets/presentation/logo.png';
import thinkImage from '../../common/components/Toolbar/assets/presentation/think.jpg';
import workerImage from '../../common/components/Toolbar/assets/presentation/worker.jpg';
import templatesImage from '../../common/components/Toolbar/assets/presentation/templates.png';
import keyboardImage from '../../common/components/Toolbar/assets/presentation/keyboard.jpg';
import reactImage from '../../common/components/Toolbar/assets/presentation/react.jpg';
import treedImage from '../../common/components/Toolbar/assets/presentation/treed.png';
import notebookImage from '../../common/components/Toolbar/assets/presentation/notebook.jpg';
import pictureImage from '../../common/components/Toolbar/assets/presentation/picture.jpg';
import successImage from '../../common/components/Toolbar/assets/presentation/success.png';
import loadingImage from '../../common/components/Toolbar/assets/presentation/loading.png';
import registerImage from '../../common/components/Toolbar/assets/presentation/register.png';
import loginImage from '../../common/components/Toolbar/assets/presentation/login.png';
import loginsuccessImage from '../../common/components/Toolbar/assets/presentation/login_success.png';
import newpresentationImage from '../../common/components/Toolbar/assets/presentation/new_presentation.png';

export const demoPresentation: Presentation = {
  title: 'SlideCraft — Демонстрация',
  slides: [
    {
      id: 'slide1',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: DESIGN_THEMES.blue_white.backgroundSize,
        position: DESIGN_THEMES.blue_white.backgroundPosition,
        isLocked: DESIGN_THEMES.blue_white.isLocked,
      },
      elements: [
        {
          id: 'title1',
          type: 'text',
          content: 'SlideCraft:',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'bottom',
          bold: true,
          position: { x: 50, y: 170 },
          size: { width: 190, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'text1',
          type: 'text',
          content: 'Создавайте',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          verticalAlign: 'bottom',
          bold: false,
          position: { x: 230, y: 170 },
          size: { width: 270, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'text2',
          type: 'text',
          content: 'впечатляющие презентации',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          verticalAlign: 'bottom',
          bold: false,
          position: { x: 50, y: 220 },
          size: { width: 500, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'text3',
          type: 'text',
          content:
            'Здравствуйте! Сегодня я рад представить вам SlideCraft - инновационное веб-приложение для создания современных и интерактивных презентаций прямо в браузере',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 50, y: 300 },
          size: { width: 550, height: 100 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: 'object',
          src: logoImage,
          position: { x: 600, y: 170 },
          size: { width: 350, height: 230 },
          smoothing: 10,
        },
        {
          id: 'text4',
          type: 'text',
          content: 'Выполнил работу: Глушков Роман ПС - 22',
          fontSize: 20,
          font: "'Times New Roman', serif",
          color: '#000000ff',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 50, y: 500 },
          size: { width: 550, height: 35 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
      ],
    },
    {
      id: 'slide2',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'title2',
          type: 'text',
          content: 'Почему SlideCraft?',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'bottom',
          bold: true,
          position: { x: 400, y: 50 },
          size: { width: 400, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'rect1',
          type: 'shape',
          shapeType: 'rectangle',
          fill: 'transparent',
          stroke: '#81c6d5',
          strokeWidth: 2,
          position: { x: 410, y: 115 },
          size: { width: 260, height: 180 },
        },
        {
          id: 'rect2',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#81c6d5',
          stroke: '#81c6d5',
          strokeWidth: 1,
          position: { x: 410, y: 115 },
          size: { width: 10, height: 180 },
        },
        {
          id: 'text5',
          type: 'text',
          content: 'Перегруженные инструменты',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          underline: true,
          position: { x: 430, y: 135 },
          size: { width: 220, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'text6',
          type: 'text',
          content: 'Сложные, но негибкие для быстрого редактирования.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 430, y: 200 },
          size: { width: 220, height: 70 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '2rect1',
          type: 'shape',
          shapeType: 'rectangle',
          fill: 'transparent',
          stroke: '#81c6d5',
          strokeWidth: 2,
          position: { x: 680, y: 115 },
          size: { width: 260, height: 180 },
        },
        {
          id: '2rect2',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#81c6d5',
          stroke: '#81c6d5',
          strokeWidth: 1,
          position: { x: 680, y: 115 },
          size: { width: 10, height: 180 },
        },
        {
          id: '2text5',
          type: 'text',
          content: 'Неудобная работа',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          underline: true,
          position: { x: 700, y: 135 },
          size: { width: 220, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '2text6',
          type: 'text',
          content: 'Отсутствие горячих клавиш, гибкой стилизации.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 700, y: 200 },
          size: { width: 220, height: 70 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '3rect1',
          type: 'shape',
          shapeType: 'rectangle',
          fill: 'transparent',
          stroke: '#81c6d5',
          strokeWidth: 2,
          position: { x: 410, y: 305 },
          size: { width: 260, height: 180 },
        },
        {
          id: '3rect2',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#81c6d5',
          stroke: '#81c6d5',
          strokeWidth: 1,
          position: { x: 410, y: 305 },
          size: { width: 10, height: 180 },
        },
        {
          id: '3text5',
          type: 'text',
          content: 'Проблема с сохранением',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          underline: true,
          verticalAlign: 'top',
          bold: false,
          position: { x: 430, y: 325 },
          size: { width: 220, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '3text6',
          type: 'text',
          content: 'Нет надежного автосохранения, риск потери данных',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 430, y: 390 },
          size: { width: 220, height: 70 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '4text1',
          type: 'text',
          content:
            'SlideCraft решает эти проблемы, объединяя удобство, функциональность и современный интерфейс.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: true,
          position: { x: 680, y: 305 },
          size: { width: 220, height: 170 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: 'object1',
          src: thinkImage,
          position: { x: 20, y: 10 },
          size: { width: 350, height: 390 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide3',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt31',
          type: 'text',
          content: 'Что такое SlideCraft?',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'bottom',
          bold: true,
          position: { x: 50, y: 170 },
          size: { width: 400, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '31',
          src: workerImage,
          position: { x: 500, y: 120 },
          size: { width: 400, height: 329 },
          smoothing: 10,
        },
        {
          id: 'tt32',
          type: 'text',
          content: 'SlideCraft',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#81c6d5',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 50, y: 270 },
          size: { width: 90, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt33',
          type: 'text',
          content: '- это полноценный онлайн-редактор презентаций.',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 140, y: 270 },
          size: { width: 450, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt34',
          type: 'text',
          content: applyListTypeToText(
            'Создавайте, редактируйте, оформляйте\nПоказывайте презентации без установки ПО\nИдеален для учебных и рабочих задач',
            'bullet_star' // ← передаём тип списка
          ),
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 50, y: 330 },
          size: { width: 450, height: 120 },
          shadow: {
            color: '0',
            blur: 0,
          },
          listType: 'bullet_star',
        },
      ],
    },
    {
      id: 'slide4',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt41',
          type: 'text',
          content: 'Мощный Редактор Презентаций',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'bottom',
          bold: true,
          position: { x: 360, y: 50 },
          size: { width: 400, height: 100 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt42',
          type: 'text',
          content: '1',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          backgroundColor: '#81c6d5',
          position: { x: 360, y: 170 },
          size: { width: 270, height: 25 },
        },
        {
          id: 'tt43',
          type: 'text',
          content: 'Панель слайдов',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 370, y: 210 },
          size: { width: 250, height: 25 },
        },
        {
          id: 'tt44',
          type: 'text',
          content: 'Интерактивные миниатюры, визуальная индикация, hover-эффекты.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 370, y: 245 },
          size: { width: 250, height: 80 },
        },
        {
          id: 'tt45',
          type: 'text',
          content: '2',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          backgroundColor: '#81c6d5',
          position: { x: 650, y: 170 },
          size: { width: 270, height: 25 },
        },
        {
          id: 'tt46',
          type: 'text',
          content: 'Гибкое управление',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 660, y: 210 },
          size: { width: 250, height: 25 },
        },
        {
          id: 'tt47',
          type: 'text',
          content: 'Drag & drop, множественное выделение, дублирование, удаление, буфер обмена.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 660, y: 245 },
          size: { width: 250, height: 80 },
        },
        {
          id: 'tt48',
          type: 'text',
          content: '3',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          backgroundColor: '#81c6d5',
          position: { x: 360, y: 360 },
          size: { width: 550, height: 25 },
        },
        {
          id: 'tt49',
          type: 'text',
          content: 'Готовые шаблоны',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 370, y: 400 },
          size: { width: 530, height: 25 },
        },
        {
          id: 'tt410',
          type: 'text',
          content: '9 типов слайдов: от титульных до сравнительных.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 370, y: 435 },
          size: { width: 530, height: 30 },
        },
        {
          type: 'image',
          id: '41',
          src: templatesImage,
          position: { x: 50, y: 50 },
          size: { width: 242, height: 450 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide6',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt61',
          type: 'text',
          content: 'Разнообразные Элементы Слайдов',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 420, y: 50 },
          size: { width: 500, height: 100 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '1rect6',
          type: 'shape',
          shapeType: 'circle',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 420, y: 170 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt62',
          type: 'text',
          content: 'Текст',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 220 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt63',
          type: 'text',
          content: 'Шрифт, размер, цвет, выравнивание, тени, фон.',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 250 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '2rect6',
          type: 'shape',
          shapeType: 'circle',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 420, y: 290 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt64',
          type: 'text',
          content: 'Изображения',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 340 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt65',
          type: 'text',
          content: 'Загрузка, эффекты, тени, скругление.',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 370 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '3rect6',
          type: 'shape',
          shapeType: 'circle',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 420, y: 410 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt66',
          type: 'text',
          content: 'Фигуры',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 460 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt67',
          type: 'text',
          content: '8 типов, SVG-рендеринг, полная стилизация.',
          fontSize: 18,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 420, y: 490 },
          size: { width: 500, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '4rect6',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#c00000',
          stroke: '#843e0d',
          strokeWidth: 10,
          position: { x: 10, y: 10 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(0, 0, 0, 0.5)',
            blur: 8,
          },
        },
        {
          id: '5rect6',
          type: 'shape',
          shapeType: 'circle',
          fill: '#ff0101',
          stroke: '#bf9100',
          strokeWidth: 8,
          position: { x: 115, y: 10 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(255, 0, 0, 0.5)',
            blur: 6,
          },
        },
        {
          id: '6rect6',
          type: 'shape',
          shapeType: 'triangle',
          fill: '#febe00',
          stroke: '#7e6000',
          strokeWidth: 6,
          position: { x: 220, y: 10 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(0, 123, 255, 0.5)',
            blur: 6,
          },
        },
        {
          id: '7rect6',
          type: 'shape',
          shapeType: 'star',
          fill: '#ffc000',
          stroke: '#2e75b5',
          strokeWidth: 5,
          position: { x: 325, y: 10 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(0, 128, 0, 0.5)',
            blur: 6,
          },
        },
        {
          id: '8rect6',
          type: 'shape',
          shapeType: 'hexagon',
          fill: '#8fd04e',
          stroke: '#a7d08c',
          strokeWidth: 4,
          position: { x: 10, y: 90 },
          size: { width: 85, height: 90 },
          shadow: {
            color: 'rgba(255, 215, 0, 0.7)',
            blur: 10,
          },
        },
        {
          id: '9rect6',
          type: 'shape',
          shapeType: 'cloud',
          fill: '#00af50',
          stroke: '#012060',
          strokeWidth: 3,
          position: { x: 115, y: 100 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(128, 0, 128, 0.6)',
            blur: 8,
          },
        },
        {
          id: '10rect6',
          type: 'shape',
          shapeType: 'callout',
          fill: '#01b0f1',
          stroke: '#222834',
          strokeWidth: 2,
          position: { x: 220, y: 100 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(255, 105, 180, 0.5)',
            blur: 6,
          },
        },
        {
          id: '11rect6',
          type: 'shape',
          shapeType: 'heart',
          fill: '#7030a0',
          stroke: '#bdd7ee',
          strokeWidth: 1,
          position: { x: 325, y: 100 },
          size: { width: 85, height: 80 },
          shadow: {
            color: 'rgba(0, 0, 0, 0.15)',
            blur: 3,
          },
        },
        {
          id: 'tt68',
          type: 'text',
          content: 'Шрифт',
          fontSize: 96,
          font: 'Impact, sans-serif',
          color: '#ffffffff',
          backgroundColor: '#000000ff',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          italic: true,
          underline: true,
          position: { x: 10, y: 190 },
          size: { width: 400, height: 170 },
          smoothing: 100,
          shadow: {
            color: 'rgba(255, 255, 255, 0.8)',
            blur: 12,
          },
        },
        {
          type: 'image',
          id: '61',
          src: reactImage,
          position: { x: 70, y: 370 },
          size: { width: 280, height: 140 },
          smoothing: 50,
          shadow: {
            color: 'rgba(0, 123, 255, 0.5)',
            blur: 6,
          },
        },
      ],
    },
    {
      id: 'slide15',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt151',
          type: 'text',
          content: 'Умные списки',
          fontSize: 42,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          position: { x: 0, y: 30 },
          size: { width: 960, height: 60 },
          shadow: {
            color: 'rgba(0, 18, 96, 0.2)',
            blur: 4,
          },
        },
        {
          id: 'marker_pyramid1',
          type: 'text',
          content: '• Точка',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 150, y: 150 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'marker_pyramid2',
          type: 'text',
          content: '○ Круг',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 180, y: 200 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'marker_pyramid3',
          type: 'text',
          content: '▪ Квадрат',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 210, y: 250 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'marker_pyramid4',
          type: 'text',
          content: '→ Стрелка',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 240, y: 300 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'marker_pyramid5',
          type: 'text',
          content: '✓ Галочка',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 270, y: 350 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'marker_pyramid6',
          type: 'text',
          content: '⭐ Звезда',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 300, y: 400 },
          size: { width: 200, height: 40 },
        },
        {
          id: 'pyramid_line',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#0071c2',
          stroke: 'none',
          strokeWidth: 0,
          position: { x: 130, y: 150 },
          size: { width: 5, height: 290 },
        },
        {
          id: 'auto_format',
          type: 'text',
          content: 'Автоформатирование',
          fontSize: 28,
          font: "'Trebuchet MS', sans-serif",
          color: '#0071c2',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          underline: true,
          position: { x: 550, y: 150 },
          size: { width: 350, height: 50 },
        },
        {
          id: 'auto_list',
          type: 'text',
          content:
            'Enter → продолжение\nСмена стиля → мгновенно\nШрифты + цвета → согласованы\nТемы → полная поддержка',
          fontSize: 20,
          font: 'Verdana, sans-serif',
          color: '#1f4e7a',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 530, y: 220 },
          size: { width: 380, height: 200 },
        },
        {
          id: 'feature_tag',
          type: 'text',
          content: '6 стилей',
          fontSize: 20,
          font: 'Impact, sans-serif',
          color: '#ffffff',
          backgroundColor: '#0071c2',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 100 },
          size: { width: 100, height: 40 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide8',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt81',
          type: 'text',
          content: 'Дизайн и Стилизация',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          position: { x: 0, y: 50 },
          size: { width: 960, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '1rect8',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#bdd7ee',
          stroke: '#0071c2',
          strokeWidth: 2,
          position: { x: 155, y: 150 },
          size: { width: 300, height: 150 },
        },
        {
          id: '4rect8',
          type: 'shape',
          shapeType: 'circle',
          fill: '#0071c2',
          stroke: '',
          strokeWidth: 0,
          position: { x: 175, y: 170 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt82',
          type: 'text',
          content: '11 готовых тем',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 235, y: 170 },
          size: { width: 200, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt83',
          type: 'text',
          content: 'Быстрый старт с профессиональным дизайном.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 175, y: 230 },
          size: { width: 270, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '2rect8',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#bdd7ee',
          stroke: '#c00000',
          strokeWidth: 2,
          position: { x: 505, y: 150 },
          size: { width: 300, height: 150 },
        },
        {
          id: '5rect8',
          type: 'shape',
          shapeType: 'circle',
          fill: '#c00000',
          stroke: '',
          strokeWidth: 0,
          position: { x: 525, y: 170 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt84',
          type: 'text',
          content: '10 цветов палитры',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 585, y: 170 },
          size: { width: 200, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt85',
          type: 'text',
          content: 'Быстрый старт с профессиональным дизайном.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 525, y: 230 },
          size: { width: 270, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '3rect8',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#bdd7ee',
          stroke: '#012060',
          strokeWidth: 2,
          position: { x: 155, y: 350 },
          size: { width: 650, height: 150 },
        },
        {
          id: 'rect8',
          type: 'shape',
          shapeType: 'circle',
          fill: '#012060',
          stroke: '',
          strokeWidth: 0,
          position: { x: 175, y: 370 },
          size: { width: 50, height: 50 },
        },
        {
          id: 'tt86',
          type: 'text',
          content: 'Единый стиль',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 235, y: 370 },
          size: { width: 200, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt87',
          type: 'text',
          content: 'Эффект теней, скругление углов для целостных презентаций.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 175, y: 430 },
          size: { width: 500, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
      ],
    },
    {
      id: 'slide9',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt91',
          type: 'text',
          content: 'Горячие Клавиши и Undo/Redo',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 70, y: 100 },
          size: { width: 700, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt92',
          type: 'text',
          content: 'Полный набор горячих клавиш для максимальной скорости работы:',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 70, y: 200 },
          size: { width: 700, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt93',
          type: 'text',
          content: applyListTypeToText(
            'Ctrl/Cmd+C: Копировать\nCtrl/Cmd+V: Вставить\nCtrl/Cmd+D: Дублировать\nDelete/BackSpace: Удалить\nCtrl/Cmd+Z: Отменить\nCtrl/Cmd+Y: Повторить',
            'bullet_disc'
          ),
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          lineHeight: 2,
          position: { x: 70, y: 250 },
          size: { width: 450, height: 230 },
          shadow: {
            color: '0',
            blur: 0,
          },
          listType: 'bullet_disc',
        },
        {
          id: 'tt94',
          type: 'text',
          content:
            'Система Undo/Redo и централизованное управление состоянием обеспечивает безопасность данных',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 70, y: 480 },
          size: { width: 840, height: 60 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '91',
          src: notebookImage,
          position: { x: 550, y: 250 },
          size: { width: 334, height: 230 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide5',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt51',
          type: 'text',
          content: 'Быстрая Навигация и Удобство',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 360, y: 50 },
          size: { width: 560, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '1rect5',
          type: 'shape',
          shapeType: 'hexagon',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 360, y: 130 },
          size: { width: 80, height: 100 },
        },
        {
          id: 'tt52',
          type: 'text',
          content: '1',
          fontSize: 28,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 360, y: 130 },
          size: { width: 80, height: 100 },
        },
        {
          id: 'tt55',
          type: 'text',
          content: 'Стрелочные клавиши',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 145 },
          size: { width: 400, height: 30 },
        },
        {
          id: 'tt56',
          type: 'text',
          content: 'Мгновенное перемещение.',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 185 },
          size: { width: 400, height: 30 },
        },
        {
          id: '2rect5',
          type: 'shape',
          shapeType: 'hexagon',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 360, y: 230 },
          size: { width: 80, height: 100 },
        },
        {
          id: 'tt53',
          type: 'text',
          content: '2',
          fontSize: 28,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 360, y: 230 },
          size: { width: 80, height: 100 },
        },
        {
          id: 'tt57',
          type: 'text',
          content: 'Smart-scrolling',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 245 },
          size: { width: 400, height: 30 },
        },
        {
          id: 'tt58',
          type: 'text',
          content: 'Плавная прокрутка.',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 285 },
          size: { width: 400, height: 30 },
        },
        {
          id: '3rect5',
          type: 'shape',
          shapeType: 'hexagon',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 4,
          position: { x: 360, y: 330 },
          size: { width: 80, height: 130 },
        },
        {
          id: 'tt54',
          type: 'text',
          content: '3',
          fontSize: 28,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 360, y: 330 },
          size: { width: 80, height: 130 },
        },
        {
          id: 'tt59',
          type: 'text',
          content: 'Без отвлечений',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 345 },
          size: { width: 400, height: 30 },
        },
        {
          id: 'tt510',
          type: 'text',
          content: 'Игнорирование навигации во время редактирования текста.',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          position: { x: 460, y: 385 },
          size: { width: 400, height: 60 },
        },
        {
          type: 'image',
          id: '51',
          src: keyboardImage,
          position: { x: 30, y: 120 },
          size: { width: 300, height: 300 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide13',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt131',
          type: 'text',
          content: 'Точность и выравнивание',
          fontSize: 48,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          position: { x: 0, y: 50 },
          size: { width: 960, height: 80 },
          shadow: {
            color: 'rgba(0, 123, 255, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'rect131',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#0071c2',
          strokeWidth: 3,
          position: { x: 50, y: 150 },
          size: { width: 400, height: 350 },
        },
        {
          id: 'tt132',
          type: 'text',
          content: 'Сетка и прилипание',
          fontSize: 28,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          underline: true,
          position: { x: 50, y: 150 },
          size: { width: 400, height: 60 },
          shadow: {
            color: 'rgba(0, 0, 0, 0.15)',
            blur: 3,
          },
        },
        {
          id: 'tt133',
          type: 'text',
          content: applyListTypeToText(
            'Сетка дизайна: 10×10 пикселей\nИнтеллектуальное прилипание (Snap to Grid)\nСнаппинг при ресайзе\nМатематическое округление',
            'bullet_check'
          ),
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 1.5,
          position: { x: 70, y: 230 },
          size: { width: 360, height: 250 },
          shadow: {
            color: '0',
            blur: 0,
          },
          listType: 'bullet_check',
        },
        {
          id: 'rect132',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#e2f0d9',
          stroke: '#00af50',
          strokeWidth: 3,
          position: { x: 510, y: 150 },
          size: { width: 400, height: 350 },
        },
        {
          id: 'tt134',
          type: 'text',
          content: 'Детали функций',
          fontSize: 28,
          font: "'Trebuchet MS', sans-serif",
          color: '#385624',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          underline: true,
          position: { x: 510, y: 150 },
          size: { width: 400, height: 60 },
          shadow: {
            color: 'rgba(0, 128, 0, 0.3)',
            blur: 5,
          },
        },
        {
          id: 'tt135',
          type: 'text',
          content: applyListTypeToText(
            'Слабо видимая сетка\nРабочая область с направляющими\nАвтовыравнивание по точкам\nПри перетаскивании и ресайзе\nТочность до 10 пикселей\nПрофессиональный результат',
            'bullet_check'
          ),
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 1.5,
          position: { x: 530, y: 230 },
          size: { width: 360, height: 250 },
          shadow: {
            color: '0',
            blur: 0,
          },
          listType: 'bullet_check',
        },
        {
          id: 'shape131',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#ffffff',
          stroke: '#c00000',
          strokeWidth: 2,
          position: { x: 70, y: 390 },
          size: { width: 100, height: 80 },
          shadow: {
            color: 'rgba(255, 0, 0, 0.3)',
            blur: 5,
          },
        },
        {
          id: 'tt1311',
          type: 'text',
          content: 'Сетка',
          fontSize: 18,
          font: 'Impact, sans-serif',
          color: '#c00000',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 70, y: 390 },
          size: { width: 100, height: 80 },
        },
        {
          id: 'shape132',
          type: 'shape',
          shapeType: 'circle',
          fill: '#ffc000',
          stroke: '#bf9100',
          strokeWidth: 3,
          position: { x: 200, y: 390 },
          size: { width: 100, height: 100 },
          shadow: {
            color: 'rgba(255, 215, 0, 0.7)',
            blur: 10,
          },
        },
        {
          id: 'tt1312',
          type: 'text',
          content: 'Snap',
          fontSize: 22,
          font: 'Impact, sans-serif',
          color: '#7e6000',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 200, y: 390 },
          size: { width: 100, height: 100 },
        },
        {
          id: 'shape133',
          type: 'shape',
          shapeType: 'triangle',
          fill: '#8fd04e',
          stroke: '#538136',
          strokeWidth: 4,
          position: { x: 330, y: 390 },
          size: { width: 100, height: 100 },
          shadow: {
            color: 'rgba(0, 128, 0, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'tt1313',
          type: 'text',
          content: 'Точность',
          fontSize: 18,
          font: 'Impact, sans-serif',
          color: '#385624',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 330, y: 390 },
          size: { width: 100, height: 100 },
        },
      ],
    },
    {
      id: 'slide7',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt71',
          type: 'text',
          content: 'Интерактивный интерфейс',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 50, y: 50 },
          size: { width: 500, height: 100 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt74',
          type: 'text',
          content: applyListTypeToText(
            'Интерактивное выделение элементов\nМножественный выбор и групповое редактирование\nПеретаскивание и изменение размера (8 ручек)\nТочное позиционирование\nInline-редактирование текста',
            'bullet_circle' // или другой тип из LIST_OPTIONS
          ),
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 50, y: 200 },
          size: { width: 450, height: 250 },
          shadow: {
            color: '0',
            blur: 0,
          },
          listType: 'bullet_circle', // добавляем это свойство
        },
        {
          type: 'image',
          id: '71',
          src: treedImage,
          position: { x: 600, y: 170 },
          size: { width: 300, height: 300 },
          smoothing: 50,
          shadow: {
            color: 'rgba(0, 123, 255, 0.5)',
            blur: 6,
          },
        },
      ],
    },
    {
      id: 'slide11',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt111',
          type: 'text',
          content: 'Автосохранение и надежность',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 50, y: 50 },
          size: { width: 700, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt112',
          type: 'text',
          content: 'С ваши данные всегда в безопасности и под контролем.',
          fontSize: 16,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 50, y: 110 },
          size: { width: 700, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '1rect11',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 50, y: 150 },
          size: { width: 215, height: 85 },
        },
        {
          id: 'tt113',
          type: 'text',
          content: 'Автосохранение',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          lineHeight: 2,
          position: { x: 50, y: 150 },
          size: { width: 215, height: 85 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '115',
          src: newpresentationImage,
          position: { x: 50, y: 235 },
          size: { width: 215, height: 134 },
          smoothing: 10,
        },
        {
          id: '2rect11',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 265, y: 235 },
          size: { width: 215, height: 85 },
        },
        {
          id: 'tt114',
          type: 'text',
          content: 'Безопасность данных',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          lineHeight: 2,
          position: { x: 265, y: 235 },
          size: { width: 215, height: 85 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '111',
          src: successImage,
          position: { x: 265, y: 197 },
          size: { width: 215, height: 38 },
          smoothing: 10,
        },
        {
          type: 'image',
          id: '113',
          src: registerImage,
          position: { x: 265, y: 320 },
          size: { width: 215, height: 140 },
          smoothing: 10,
        },
        {
          id: '3rect11',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 480, y: 320 },
          size: { width: 215, height: 85 },
        },
        {
          id: 'tt115',
          type: 'text',
          content: 'Система уведомлений',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          lineHeight: 2,
          position: { x: 480, y: 320 },
          size: { width: 215, height: 85 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '114',
          src: loginsuccessImage,
          position: { x: 480, y: 282 },
          size: { width: 215, height: 38 },
          smoothing: 10,
        },
        {
          type: 'image',
          id: '112',
          src: loginImage,
          position: { x: 480, y: 405 },
          size: { width: 215, height: 116 },
          smoothing: 10,
        },
        {
          id: '4rect11',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 695, y: 405 },
          size: { width: 215, height: 85 },
        },
        {
          id: 'tt116',
          type: 'text',
          content: 'Высокая надежность',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          lineHeight: 2,
          position: { x: 695, y: 405 },
          size: { width: 215, height: 85 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '116',
          src: loadingImage,
          position: { x: 695, y: 366 },
          size: { width: 215, height: 39 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide14',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt141',
          type: 'text',
          content: 'Экспорт и публикация',
          fontSize: 42,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          position: { x: 0, y: 30 },
          size: { width: 960, height: 60 },
          shadow: {
            color: 'rgba(0, 123, 255, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'pdf_icon',
          type: 'text',
          content: '📄',
          fontSize: 80,
          font: 'Arial, sans-serif',
          color: '#ffffff',
          backgroundColor: '#c00000',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 120 },
          size: { width: 120, height: 150 },
          smoothing: 10,
          shadow: {
            color: 'rgba(192, 0, 0, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'doc1',
          type: 'text',
          content: '',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#000000',
          backgroundColor: '#bfbfbf',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 200, y: 110 },
          size: { width: 140, height: 180 },
          smoothing: 5,
          shadow: {
            color: 'rgba(0, 0, 0, 0.3)',
            blur: 5,
          },
        },
        {
          id: 'doc2',
          type: 'text',
          content: '',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#000000',
          backgroundColor: '#a5a5a5',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 220, y: 100 },
          size: { width: 140, height: 180 },
          smoothing: 5,
          shadow: {
            color: 'rgba(0, 0, 0, 0.2)',
            blur: 4,
          },
        },
        {
          id: 'doc3',
          type: 'text',
          content: '',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#000000',
          backgroundColor: '#7f7f7f',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 240, y: 90 },
          size: { width: 140, height: 180 },
          smoothing: 5,
          shadow: {
            color: 'rgba(0, 0, 0, 0.4)',
            blur: 6,
          },
        },
        {
          id: 'tt142',
          type: 'text',
          content: 'Экспорт в PDF',
          fontSize: 32,
          font: "'Trebuchet MS', sans-serif",
          color: '#012060',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          underline: true,
          position: { x: 400, y: 100 },
          size: { width: 500, height: 50 },
          shadow: {
            color: 'rgba(0, 18, 96, 0.3)',
            blur: 5,
          },
        },
        {
          id: 'features_box',
          type: 'shape',
          shapeType: 'callout',
          fill: '#ffffff',
          stroke: '#0071c2',
          strokeWidth: 3,
          position: { x: 400, y: 170 },
          size: { width: 500, height: 300 },
          shadow: {
            color: 'rgba(0, 113, 194, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'tt143',
          type: 'text',
          content: applyListTypeToText(
            'Качественный PDF-рендеринг\nМногостраничный документ\nСохранение всех стилей\nВизуальные эффекты и тени\nГотов к печати и публикации',
            'bullet_square'
          ),
          fontSize: 22,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 1.8,
          position: { x: 430, y: 190 },
          size: { width: 440, height: 260 },
          listType: 'bullet_square',
        },
        {
          id: 'quality_badge',
          type: 'text',
          content: '⭐',
          fontSize: 60,
          font: 'Arial, sans-serif',
          color: '#ffc000',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 300 },
          size: { width: 100, height: 100 },
          shadow: {
            color: 'rgba(255, 192, 0, 0.7)',
            blur: 10,
          },
        },
        {
          id: 'export_button',
          type: 'text',
          content: 'ЭКСПОРТИРОВАТЬ',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#ffffff',
          backgroundColor: '#0071c2',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 460 },
          size: { width: 200, height: 60 },
          smoothing: 10,
          shadow: {
            color: 'rgba(0, 113, 194, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'arrow',
          type: 'shape',
          shapeType: 'triangle',
          fill: '#01b0f1',
          stroke: '#0071c2',
          strokeWidth: 2,
          position: { x: 260, y: 480 },
          size: { width: 40, height: 40 },
          shadow: {
            color: 'rgba(1, 176, 241, 0.5)',
            blur: 6,
          },
        },
        {
          id: 'tt144',
          type: 'text',
          content: 'Профессиональный результ ат',
          fontSize: 20,
          font: "'Brush Script MT', cursive",
          color: '#01b0f1',
          align: 'left',
          verticalAlign: 'middle',
          bold: true,
          italic: true,
          position: { x: 310, y: 480 },
          size: { width: 400, height: 40 },
          shadow: {
            color: 'rgba(1, 176, 241, 0.3)',
            blur: 4,
          },
        },
        {
          id: 'pdf_text',
          type: 'text',
          content: 'PDF',
          fontSize: 28,
          font: 'Impact, sans-serif',
          color: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 150 },
          size: { width: 120, height: 80 },
          shadow: {
            color: 'rgba(0, 0, 0, 0.3)',
            blur: 5,
          },
        },
        {
          id: 'tt145',
          type: 'text',
          content: 'Качество',
          fontSize: 20,
          font: 'Impact, sans-serif',
          color: '#bf9100',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 50, y: 350 },
          size: { width: 100, height: 30 },
        },
      ],
    },
    {
      id: 'slide10',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt101',
          type: 'text',
          content: 'Режим Презентации',
          fontSize: 36,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          position: { x: 50, y: 50 },
          size: { width: 700, height: 50 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: 'tt102',
          type: 'text',
          content: 'SlideCraft обеспечивает безупречное отображение ваших материалов:',
          fontSize: 16,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 50, y: 110 },
          size: { width: 700, height: 30 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '1rect10',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 50, y: 150 },
          size: { width: 500, height: 100 },
        },
        {
          id: 'tt103',
          type: 'text',
          content: 'Полноэкранный Режим \nМаксимальное погружение аудитории.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 60, y: 160 },
          size: { width: 480, height: 80 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '2rect10',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 50, y: 250 },
          size: { width: 500, height: 100 },
        },
        {
          id: 'tt104',
          type: 'text',
          content: 'Гибкое Управление \nЛегкое переключение слайдов.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 60, y: 260 },
          size: { width: 480, height: 80 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          id: '3rect10',
          type: 'shape',
          shapeType: 'rectangle',
          fill: '#daedf3',
          stroke: '#1f4e7a',
          strokeWidth: 1,
          position: { x: 50, y: 350 },
          size: { width: 500, height: 100 },
        },
        {
          id: 'tt105',
          type: 'text',
          content: 'Сохранение Пропорций \nДизайн всегда выглядит как задумано.',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          lineHeight: 2,
          position: { x: 60, y: 360 },
          size: { width: 480, height: 80 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
        {
          type: 'image',
          id: '101',
          src: pictureImage,
          position: { x: 560, y: 150 },
          size: { width: 300, height: 300 },
          smoothing: 10,
        },
      ],
    },
    {
      id: 'slide12',
      background: {
        type: 'image',
        value: DESIGN_THEMES.blue_white.backgroundImage!,
        size: 'cover',
        position: 'center',
      },
      elements: [
        {
          id: 'tt1211',
          type: 'text',
          content: 'Спасибо за внимание!',
          fontSize: 96,
          font: "'Trebuchet MS', sans-serif",
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          position: { x: 0, y: 0 },
          size: { width: 960, height: 270 },
          shadow: {
            color: 'rgba(0, 0, 0, 0.5)',
            blur: 8,
          },
        },
        {
          id: 'tt1212',
          type: 'text',
          content: 'Готов ответить на вопросы',
          fontSize: 48,
          font: 'Arial, sans-serif',
          color: '#203864',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          position: { x: 0, y: 280 },
          size: { width: 960, height: 100 },
          shadow: {
            color: '0',
            blur: 0,
          },
        },
      ],
    },
  ],
  currentSlideId: 'slide1',
  selectedSlideIds: ['slide1'],
};
