import { Slide } from '../types/presentation';

export const slideTitle: Slide = {
  id: 'slide1',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide1_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 144, y: 100 },
      size: { width: 660, height: 180 },
      font: 'Arial',
      fontSize: 60,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide1_desc1',
      content: '',
      placeholder: 'Подзаголовок слайда',
      position: { x: 144, y: 290 },
      size: { width: 660, height: 120 },
      font: 'Arial',
      fontSize: 24,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideTitleAndObject: Slide = {
  id: 'slide2',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide2_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 818, height: 100 },
      font: 'Arial',
      fontSize: 44,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide2_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 150 },
      size: { width: 818, height: 330 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideSectionHeader: Slide = {
  id: 'slide3',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide3_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 75, y: 140 },
      size: { width: 808, height: 200 },
      font: 'Arial',
      fontSize: 44,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide3_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 75, y: 345 },
      size: { width: 808, height: 130 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideTwoObjects: Slide = {
  id: 'slide4',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide4_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 818, height: 100 },
      font: 'Arial',
      fontSize: 44,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide4_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 150 },
      size: { width: 404, height: 330 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide4_caption2',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 484, y: 150 },
      size: { width: 404, height: 330 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideComparison: Slide = {
  id: 'slide5',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide5_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 818, height: 100 },
      font: 'Arial',
      fontSize: 44,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide5_left_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 145 },
      size: { width: 404, height: 50 },
      font: 'Arial',
      fontSize: 24,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide5_left_caption2',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 200 },
      size: { width: 404, height: 280 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide5_right_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 484, y: 145 },
      size: { width: 404, height: 50 },
      font: 'Arial',
      fontSize: 24,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide5_right_caption2',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 484, y: 200 },
      size: { width: 404, height: 280 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideJustHeadline: Slide = {
  id: 'slide6',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide6_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 818, height: 100 },
      font: 'Arial',
      fontSize: 44,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideEmpty: Slide = {
  id: 'slide7',
  background: { type: 'color', value: '#ffffff' },
  elements: [],
};

export const slideObjectWithSignature: Slide = {
  id: 'slide8',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide8_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 354, height: 160 },
      font: 'Arial',
      fontSize: 32,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide8_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 200 },
      size: { width: 354, height: 280 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide8_caption2',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 454, y: 90 },
      size: { width: 434, height: 390 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};

export const slideDrawingWithCaption: Slide = {
  id: 'slide9',
  background: { type: 'color', value: '#ffffff' },
  elements: [
    {
      type: 'text',
      id: 'slide9_title1',
      content: '',
      placeholder: 'Заголовок слайда',
      position: { x: 70, y: 40 },
      size: { width: 354, height: 160 },
      font: 'Arial',
      fontSize: 32,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide9_caption1',
      content: '',
      placeholder: 'Текст слайда',
      position: { x: 70, y: 200 },
      size: { width: 354, height: 280 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'slide9_drawing1',
      content: '',
      placeholder: 'Вставка рисунка',
      position: { x: 454, y: 90 },
      size: { width: 434, height: 390 },
      font: 'Arial',
      fontSize: 28,
      color: '#000000ff',
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
};
